"""ASS subtitle generation for Video2Subtitles.

Provides functions to generate ASS subtitle text from SubtitleSegment lists,
supporting source-only, translated, and bilingual layouts with style presets.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

from job_models import SubtitleSegment, SubtitleStyle

ASS_HEADER_TEMPLATE = """[Script Info]
; ASS subtitle generated by Video2Subtitles
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
{styles}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


_STYLE_LINE = "Style: {name},{fontname},{fontsize},{primary},{secondary},{outline},{back},{bold},0,0,0,100,100,0,0,1,{outline_w},{shadow},{align},10,10,{margin_v},0"

_PRIMARY_LAYER = 20
_SECONDARY_LAYER = 10


def _secondary_margin_v(style: SubtitleStyle,
                        translation_scale: float = 1.0) -> int:
    """Keep bilingual lines from occupying the same screen position."""
    line_gap = int(max(18, style.font_size * translation_scale + style.outline * 4 + style.shadow))
    return max(0, int(style.margin_v) + line_gap)


def _style_line(name: str, style: SubtitleStyle) -> str:
    return _STYLE_LINE.format(
        name=name,
        fontname=style.font_family,
        fontsize=style.font_size,
        primary=style.primary_color,
        secondary=style.secondary_color,
        outline=style.outline_color,
        back=style.background_color,
        bold=int(style.bold),
        outline_w=f"{style.outline:.1f}",
        shadow=f"{style.shadow:.1f}",
        align=style.alignment,
        margin_v=style.margin_v,
    )


def _escape_ass(text: str) -> str:
    text = text.replace("\\", "\\\\")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace("\n", "\\N")
    return text


def _format_time(seconds: float) -> str:
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = seconds % 60
    return f"{hours}:{minutes:02d}:{secs:05.2f}"


def _dialog_line(layer: int, start: float, end: float, style: str, text: str) -> str:
    return f"Dialogue: {layer},{_format_time(start)},{_format_time(end)},{style},,0,0,0,,{text}"


def ass_header(style: SubtitleStyle, source_scale: float = 0.8,
               translation_scale: float = 1.0) -> str:
    primary_name = "Default"
    source_name = "Source"
    translation_name = "Translation"

    base_style = _style_line(primary_name, style)

    source_style_adj = SubtitleStyle(
        preset=style.preset,
        font_family=style.font_family,
        font_size=max(12, int(style.font_size * source_scale)),
        primary_color=style.primary_color,
        secondary_color=style.secondary_color,
        outline_color=style.outline_color,
        background_color=style.background_color,
        outline=style.outline,
        shadow=style.shadow,
        margin_v=_secondary_margin_v(style, translation_scale),
        alignment=style.alignment,
        bold=style.bold,
    )
    source_line = _style_line(source_name, source_style_adj)

    trans_style_adj = SubtitleStyle(
        preset=style.preset,
        font_family=style.font_family,
        font_size=max(12, int(style.font_size * translation_scale)),
        primary_color="&H00FFFF99",
        secondary_color=style.secondary_color,
        outline_color=style.outline_color,
        background_color=style.background_color,
        outline=style.outline,
        shadow=style.shadow,
        margin_v=style.margin_v,
        alignment=style.alignment,
        bold=style.bold,
    )
    trans_line = _style_line(translation_name, trans_style_adj)

    styles = "\n".join([base_style, source_line, trans_line])
    return ASS_HEADER_TEMPLATE.format(styles=styles)


def segments_to_ass(segments: List[SubtitleSegment], style: SubtitleStyle,
                    mode: str = "source") -> str:
    """Generate ASS content from subtitle segments.

    Args:
        segments: List of SubtitleSegment.
        style: Subtitle style configuration.
        mode: One of "source", "translated", "bilingual".

    Returns:
        Full ASS file content as string.
    """
    header = ass_header(style)
    lines: List[str] = [header]

    for seg in segments:
        source_text = _escape_ass(seg.text)
        trans_text = _escape_ass(seg.translation) if seg.translation else ""

        if mode == "source":
            lines.append(_dialog_line(_PRIMARY_LAYER, seg.start, seg.end, "Default", source_text))
        elif mode == "translated":
            if not trans_text:
                continue
            lines.append(_dialog_line(_PRIMARY_LAYER, seg.start, seg.end, "Default", trans_text))
        elif mode == "bilingual":
            if trans_text:
                lines.append(_dialog_line(_SECONDARY_LAYER, seg.start, seg.end, "Source", source_text))
                lines.append(_dialog_line(_PRIMARY_LAYER, seg.start, seg.end, "Translation", trans_text))
            else:
                lines.append(_dialog_line(_PRIMARY_LAYER, seg.start, seg.end, "Default", source_text))

    return "\n".join(lines)


def save_ass(content: str, output_path: Path) -> None:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
